# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
# Author: File autogenerated by brickshelper
# Purpose: The following file contains the modules for the system

module "motivus_workers" {
  providers = {
    oci.home = oci.home
  }
  source = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## MOTIVUS_WORKERS SPECIFIC VARIABLES ##############
  is_root_child           = var.motivus_workers_is_root_child
  compartment_name        = var.motivus_workers_compartment_name
  compartment_description = var.motivus_workers_compartment_description
  enable_delete           = var.motivus_workers_enable_delete
  sleep_timer             = var.motivus_workers_sleep_timer
  ############## MOTIVUS_WORKERS SPECIFIC VARIABLES ##############
}


module "hub01" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.motivus_workers]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## HUB01 SPECIFIC VARIABLES ##############
  parent_compartment_name = var.hub01_parent_compartment_name
  compartment_name        = var.hub01_compartment_name
  compartment_description = var.hub01_compartment_description
  enable_delete           = var.hub01_enable_delete
  sleep_timer             = var.hub01_sleep_timer
  ############## HUB01 SPECIFIC VARIABLES ##############
}


module "hub01_artifacts" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.hub01]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## HUB01_ARTIFACTS SPECIFIC VARIABLES ##############
  parent_compartment_name = var.hub01_artifacts_parent_compartment_name
  compartment_name        = var.hub01_artifacts_compartment_name
  compartment_description = var.hub01_artifacts_compartment_description
  enable_delete           = var.hub01_artifacts_enable_delete
  sleep_timer             = var.hub01_artifacts_sleep_timer
  ############## HUB01_ARTIFACTS SPECIFIC VARIABLES ##############
}


module "hub01_network" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.hub01]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## HUB01_NETWORK SPECIFIC VARIABLES ##############
  parent_compartment_name = var.hub01_network_parent_compartment_name
  compartment_name        = var.hub01_network_compartment_name
  compartment_description = var.hub01_network_compartment_description
  enable_delete           = var.hub01_network_enable_delete
  sleep_timer             = var.hub01_network_sleep_timer
  ############## HUB01_NETWORK SPECIFIC VARIABLES ##############
}


module "prd01" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.motivus_workers]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## PRD01 SPECIFIC VARIABLES ##############
  parent_compartment_name = var.prd01_parent_compartment_name
  compartment_name        = var.prd01_compartment_name
  compartment_description = var.prd01_compartment_description
  enable_delete           = var.prd01_enable_delete
  sleep_timer             = var.prd01_sleep_timer
  ############## PRD01 SPECIFIC VARIABLES ##############
}


module "prd01_artifacts" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.prd01]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## PRD01_ARTIFACTS SPECIFIC VARIABLES ##############
  parent_compartment_name = var.prd01_artifacts_parent_compartment_name
  compartment_name        = var.prd01_artifacts_compartment_name
  compartment_description = var.prd01_artifacts_compartment_description
  enable_delete           = var.prd01_artifacts_enable_delete
  sleep_timer             = var.prd01_artifacts_sleep_timer
  ############## PRD01_ARTIFACTS SPECIFIC VARIABLES ##############
}


module "prd01_network" {
  providers = {
    oci.home = oci.home
  }
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-compartment.git?ref=v1.0.3"
  depends_on = [module.prd01]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## PRD01_NETWORK SPECIFIC VARIABLES ##############
  parent_compartment_name = var.prd01_network_parent_compartment_name
  compartment_name        = var.prd01_network_compartment_name
  compartment_description = var.prd01_network_compartment_description
  enable_delete           = var.prd01_network_enable_delete
  sleep_timer             = var.prd01_network_sleep_timer
  ############## PRD01_NETWORK SPECIFIC VARIABLES ##############
}

