# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
# Author: File autogenerated by brickshelper
# Purpose: The following file contains the modules for the system

module "hub01" {
  source = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-network-artifacts.git?ref=v2.0.1"
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## HUB01 SPECIFIC VARIABLES ##############
  vcn_cidr_blocks                    = var.hub01_vcn_cidr_blocks
  private_subnet_cidr_block_map      = var.hub01_private_subnet_cidr_block_map
  public_subnet_cidr_block_map       = var.hub01_public_subnet_cidr_block_map
  vcn_display_name                   = var.hub01_vcn_display_name
  vcn_network_compartment_name       = var.hub01_vcn_network_compartment_name
  dhcp_options_display_name          = var.hub01_dhcp_options_display_name
  custom_search_domain               = var.hub01_custom_search_domain
  private_route_table_display_name   = var.hub01_private_route_table_display_name
  public_route_table_display_name    = var.hub01_public_route_table_display_name
  private_security_list_display_name = var.hub01_private_security_list_display_name
  public_security_list_display_name  = var.hub01_public_security_list_display_name
  service_gateway_display_name       = var.hub01_service_gateway_display_name
  nat_gateway_display_name           = var.hub01_nat_gateway_display_name
  internet_gateway_display_name      = var.hub01_internet_gateway_display_name
  drg_display_name                   = var.hub01_drg_display_name
  peered_vcn_cidr_blocks             = var.hub01_peered_vcn_cidr_blocks
  is_spoke                           = var.hub01_is_spoke
  ############## HUB01 SPECIFIC VARIABLES ##############
}


module "prd01" {
  source     = "git::ssh://git@github.com/oracle-devrel/terraform-oci-cloudbricks-network-artifacts.git?ref=v2.0.1"
  depends_on = [module.hub01]
  ############## PROVIDER SPECIFIC VARIABLES ##############
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  ############## PROVIDER SPECIFIC VARIABLES ##############
  ############## PRD01 SPECIFIC VARIABLES ##############
  vcn_cidr_blocks                    = var.prd01_vcn_cidr_blocks
  private_subnet_cidr_block_map      = var.prd01_private_subnet_cidr_block_map
  public_subnet_cidr_block_map       = var.prd01_public_subnet_cidr_block_map
  vcn_display_name                   = var.prd01_vcn_display_name
  vcn_network_compartment_name       = var.prd01_vcn_network_compartment_name
  dhcp_options_display_name          = var.prd01_dhcp_options_display_name
  custom_search_domain               = var.prd01_custom_search_domain
  private_route_table_display_name   = var.prd01_private_route_table_display_name
  public_route_table_display_name    = var.prd01_public_route_table_display_name
  private_security_list_display_name = var.prd01_private_security_list_display_name
  public_security_list_display_name  = var.prd01_public_security_list_display_name
  service_gateway_display_name       = var.prd01_service_gateway_display_name
  nat_gateway_display_name           = var.prd01_nat_gateway_display_name
  internet_gateway_display_name      = var.prd01_internet_gateway_display_name
  drg_display_name                   = var.hub01_drg_display_name
  hub_vcn_compartment_name           = var.hub01_vcn_network_compartment_name
  hub_vcn_display_name               = var.hub01_vcn_display_name
  is_spoke                           = var.prd01_is_spoke
  ############## PRD01 SPECIFIC VARIABLES ##############
}

