# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
# Author: File autogenerated by brickshelper
# Purpose: The following file contains the outputs for the system


output "hub01_vcn" {
  description = "VCN Object"
  value       = module.hub01.vcn
}

output "hub01_private_subnets" {
  description = "Private subnets created"
  value       = module.hub01.private_subnets
}

output "hub01_public_subnets" {
  description = "Public subnets created"
  value       = module.hub01.public_subnets
}

output "hub01_network_compartment" {
  description = "Compartment where network resides on"
  value       = module.hub01.network_compartment
}

output "hub01_service_gateway" {
  description = "Service Gateway component"
  value       = module.hub01.service_gateway
}

output "hub01_nat_gateway" {
  description = "NAT Gateway component"
  value       = module.hub01.nat_gateway

}

output "hub01_internet_gateway" {
  description = "Internet Gateway component"
  value       = module.hub01.internet_gateway
}

output "hub01_private_security_list" {
  description = "Private Security List associated to subnets"
  value       = module.hub01.private_security_list
}

output "hub01_public_security_list" {
  description = "Public Security List associated to subnets"
  value       = module.hub01.public_security_list
}

output "hub01_private_route_table" {
  description = "Private Route Table associated to subnets"
  value       = module.hub01.private_route_table
}

output "hub01_public_route_table" {
  description = "Public Route Table assocaited to subnets"
  value       = module.hub01.public_route_table
}

output "hub01_dhcp_options" {
  description = "DHCP Options associated to VCN"
  value       = module.hub01.dhcp_options
}

output "hub01_dynamic_routing_gateway" {
  description = "Dynamic Routing Gateway Associated to VCNs"
  value       = module.hub01.dynamic_routing_gateway
}


output "prd01_vcn" {
  description = "VCN Object"
  value       = module.prd01.vcn
}

output "prd01_private_subnets" {
  description = "Private subnets created"
  value       = module.prd01.private_subnets
}

output "prd01_public_subnets" {
  description = "Public subnets created"
  value       = module.prd01.public_subnets
}

output "prd01_network_compartment" {
  description = "Compartment where network resides on"
  value       = module.prd01.network_compartment
}

output "prd01_service_gateway" {
  description = "Service Gateway component"
  value       = module.prd01.service_gateway
}

output "prd01_nat_gateway" {
  description = "NAT Gateway component"
  value       = module.prd01.nat_gateway

}

output "prd01_internet_gateway" {
  description = "Internet Gateway component"
  value       = module.prd01.internet_gateway
}

output "prd01_private_security_list" {
  description = "Private Security List associated to subnets"
  value       = module.prd01.private_security_list
}

output "prd01_public_security_list" {
  description = "Public Security List associated to subnets"
  value       = module.prd01.public_security_list
}

output "prd01_private_route_table" {
  description = "Private Route Table associated to subnets"
  value       = module.prd01.private_route_table
}

output "prd01_public_route_table" {
  description = "Public Route Table assocaited to subnets"
  value       = module.prd01.public_route_table
}

output "prd01_dhcp_options" {
  description = "DHCP Options associated to VCN"
  value       = module.prd01.dhcp_options
}

output "prd01_dynamic_routing_gateway" {
  description = "Dynamic Routing Gateway Associated to VCNs"
  value       = module.prd01.dynamic_routing_gateway
}

